# Generated by Django 4.2.3 on 2023-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
