# Generated by Django 4.2.3 on 2023-07-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
